config/routes.rb
Rails.application.routes.draw do
    devise_for :users

    devise_scope :user do
        authenticated :user do
            root 'home#index', as: :authenticated_root
        end

        unauthenticated do
            root 'devise/sessions#new', as: :unauthenticated_root
        end
    end
  
    root 'home#index'

    patch 'tasks/update_status/:id', to: 'tasks#update_status', as: 'update_status' 
    get 'tasks/tasks_list', to: 'tasks#tasks_list', as: 'tasks_list' 
    resources :tasks
    resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :nullify
    validates :name, presence: true, uniqueness: {scope: :user_id}
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category, optional: true

    validate :uniqueness_to_user
    # validate :unique_to_user
    validates :title, presence: true
    validates :body, presence: true
    validates :deadline, presence: true

    def uniqueness_to_user 
        sql = <<~SQL
            SELECT *
            FROM tasks, categories, users 
            WHERE categories.user_id = '#{User.current.id}' AND tasks.category_id = categories.id
            AND tasks.title = '#{title}'
        SQL

        records = ActiveRecord::Base.connection.exec_query(sql).to_a
        if (records.present? && new_record?)
            errors.add(:title, "already exists")    
        end
    end

    # def user
    #     category.user
    # end

    # def unique_to_user
    #     results = user.tasks.where(title: title)

    #     errors.add(:title, "already exists") if results.present?
    # end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :tasks, through: :categories

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token

    # protect_from_forgery with: :exception
    # protect_from_forgery prepend: true
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

    before_action :set_current_user

    def set_current_user
          User.current = current_user
    end

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
          end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = current_user.categories.order("updated_at DESC")
        @tasks = current_user.tasks
    end

    def new
        @categories = current_user.categories
        @tasks = current_user.tasks                        
        @category = Category.new
    end

    
    #for destroying categories, corresponding fk to tasks tables should be deleted
    def show
        @categories = current_user.categories
        @tasks = current_user.tasks 
        @category = Category.find(params[:id])
    end

    def create
        @categories = current_user.categories
        @tasks = current_user.tasks 
        @category = current_user.categories.build(category_params)

        if @category.valid?
            @category.save
            redirect_to root_path, notice: 'Category was created successfully.'
            
        else
            render :new
        end
    end

    def edit
        @categories = current_user.categories
        @tasks = current_user.tasks
        @category = Category.find(params[:id])
    end

    def update
        @categories = current_user.categories
        @tasks = current_user.tasks
        @category = Category.find(params[:id])
        if @category.update(category_params)
            redirect_to root_path, notice: 'Category was updated successfully.'
        else
            render :edit
        end
    end

    
    def destroy
        @categories = current_user.categories
        @tasks = current_user.tasks
        @category = Category.find(params[:id])
        @category.destroy
        redirect_to root_path, notice: 'Category was deleted successfully.'
    end
    

    private
    def category_params
        params.require(:category).permit(:name, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    skip_before_action :authenticate_user!, :only => [:index]
    
    def index
        
        @categories = Category.where(user_id: current_user.id).order("updated_at DESC")
        @tasks = current_user.tasks
    
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = current_user.tasks.order("updated_at DESC")
        @categories = current_user.categories
    end

    def tasks_list
        @tasks = current_user.tasks.order("deadline ASC")
        @categories = current_user.categories
    end

    def new
        @categories = current_user.categories
        @tasks = current_user.tasks         
        @task = Task.new
    end

    def show
        @categories = current_user.categories
        @tasks = current_user.tasks 
        @task = Task.find(params[:id])
    end

    def create
        @categories = current_user.categories
        @tasks = current_user.tasks 
        @task = Task.new(task_params)

        if @task.valid?
            @task.save
            redirect_to root_path, notice: 'Task was created successfully.'
            
        else
            render :new
        end
    end

    def edit
        @categories = current_user.categories
        @tasks = current_user.tasks 
        @task = Task.find(params[:id])
    end

    def update
        @categories = current_user.categories
        @tasks = current_user.tasks 
        @task = Task.find(params[:id])
        if @task.update(task_params)
            redirect_to root_path, notice: 'Task was updated successfully.'
        else
            render :edit
        end
    end

    def update_status
        @categories = current_user.categories
        @tasks = current_user.tasks 
        @task = Task.find(params[:id])
        @task.update(status: params[:status])
        
    end

    def destroy
        @categories = current_user.categories
        @tasks = current_user.tasks 
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to root_path, notice: 'Task was deleted successfully.'
    end

    private
    def task_params
        params.require(:task).permit(:title, :body, :deadline, :category_id, :status)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/edit.html.erb
<div class='container'>
    <%= form_with scope: :category, url: category_path, method: :put, local: true do |f| %>
    <%# url attr is where the user is redirected once the form is submitted
    url: use alias for value; you can view aliases by issuing the command:
    rails routes outside rails console %>

    <div>
        <% if @category.errors.any? %>
        <ul>
            <% @category.errors.full_messages.each do |msg| %>
                <li class="alert alert-danger" role="alert" ><%= msg %></li>
            <% end %>
        </ul>
        <% end %>
    </div>


    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.text_field :user_id, value: current_user.id, type: :hidden %>
    </div>

    <div>
        <%= f.submit :Update, class: 'btn btn-primary' %>
    </div>

    <% end %>
</div>

app/views/categories/index.html.erb
<div class='mainboard-header'>
    <h3>Categories</h3>
</div>
<br>
<div class="table table-responsive-lg categories-table">
    <% @categories.each do |categ| %>
        <div class='category-div'>
            <div class='category-div-header'>
                <h4 data-link="<%= category_path(categ) %>" class='mylink'><%= categ.name %></h4>
                <div><span><%= categ.tasks.count %></span></div>
            </div>
            
            <ul class="list-group list-group-flush">
            <% categ.tasks.each do |task| %>
                <li data-link="<%= task_path(task) %>" class='mylink list-group-item'><%= task.title %></li>
            <% end %>
            <%= link_to "+", new_task_path, class: 'add-task-in-categ' %>
            </ul>
        </div>
    <% end %>
    
</div>
<br>
<div class='create-category'>
    <%= link_to "New Category", new_category_path %>
</div>





<!--this is probably not needed, redundant-->

app/views/categories/new.html.erb
<div class='container'>
        <%= form_with scope: :category, url: categories_path, local: true do |f| %>
        <%# url attr is where the user is redirected once the form is submitted
        url: use alias for value; you can view aliases by issuing the command:
        rails routes outside rails console %>

    <div>
        <% if @category.errors.any? %>
        <ul>
            <% @category.errors.full_messages.each do |msg| %>
                <li class="alert alert-danger" role="alert" ><%= msg %></li>
            <% end %>
        </ul>
        <% end %>
    </div>


    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.text_field :user_id, id: :category_user_id, value: current_user.id, type: :hidden %>
    </div>


    <div>
        <%= f.submit :Post, class: 'btn btn-primary'%>
    </div>

<% end %>
</div>

app/views/categories/show.html.erb
<div class='container'>
    <br/>
    <h1><%= @category.name %></h1>

    <%= link_to 'Home', root_path, class: 'btn btn-primary'%>
    <%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-primary'%>
    <%= link_to 'Delete', @category, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
</div>

app/views/home/index.html.erb
<div class='mainboard-container'>
    <div class='mainboard'>
        <div class='mainboard-header'>
            <h3>Tasks</h3>
            <div class="form-group scope">
                <select class="form-control" id="sel1">
                    <option selected>Today</option>
                    <option>This Week</option>
                    <option>This Month</option>
                    <option>This Year</option>
                </select>
            </div>
        </div>
        <div class='status-container'>

            <div class='status' id='unfinished' onmouseover="this.style.overflowY='auto'" onmouseout="this.style.overflowY='hidden'">
                <div class='status-header'>
                    <h5>To Do</h5>
                    <div class='task-counter'><p><%= @tasks.where(status: "unfinished").count %></p></div>
                </div>
                <%= link_to "+", new_task_path, type: :button, class: 'add-task' %>
                <% @tasks.where(status: "unfinished").order("deadline ASC").each do |todo| %>
                    <div class='mytask draggable' draggable='true' id='<%= todo.id %>'>
                        <div class='mytask-title'>
                            <div>
                                <div class='categ-marker'></div>
                                <td><%= link_to todo.title, todo, class: 'mytask-title-title'%></td>
                            </div>
                            <span class='mytask-deadline'><%= todo.deadline.strftime("%B %d, %Y") %></span>
                        </div>
                        <div class='mytask-body'><%= todo.body.first(200) %></div>
                    </div>
                <% end %>
            </div>

            <div class='status' id='in_progress' onmouseover="this.style.overflowY='auto'" onmouseout="this.style.overflowY='hidden'">
                <div class='status-header'>
                    <h5>In Progress</h5>
                    <div class='task-counter'><p><%= @tasks.where(status: "in_progress").count %></p></div>
                </div>
                <%= link_to "+", new_task_path, type: :button, class: 'add-task' %>
                <% @tasks.where(status: "in_progress").order("deadline ASC").each do |todo| %>
                    <div class='mytask draggable' draggable='true' id='<%= todo.id %>'>
                        <div class='mytask-title'>
                            <div>
                                <div class='categ-marker'></div>
                                <td><%= link_to todo.title, todo, class: 'mytask-title-title'%></td>
                            </div>
                            <span class='mytask-deadline'><%= todo.deadline.strftime("%B %d, %Y") %></span>
                        </div>
                        <div class='mytask-body'><%= todo.body.first(200) %></div>
                    </div>
                <% end %>
            </div>

            <div class='status' id='completed' onmouseover="this.style.overflowY='auto'" onmouseout="this.style.overflowY='hidden'">
                <div class='status-header'>
                    <h5>Completed</h5>
                    <div class='task-counter'><p><%= @tasks.where(status: "completed").count %></p></div>
                </div>
                <%= link_to "+", new_task_path, type: :button, class: 'add-task' %>
                <% @tasks.where(status: "completed").order("deadline ASC").each do |todo| %>
                    <div class='mytask draggable' draggable='true' id='<%= todo.id %>'>
                        <div class='mytask-title'>
                            <div>
                                <div class='categ-marker'></div>
                                <td><%= link_to todo.title, todo, class: 'mytask-title-title'%></td>
                            </div>
                            <span class='mytask-deadline'><%= todo.deadline.strftime("%B %d, %Y") %></span>
                        </div>
                        <div class='mytask-body'><%= todo.body.first(200) %></div>
                    </div>
                <% end %>
            </div>

        </div>
        
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <!--bootstap 4.6.0-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

        <title>spaces</title>
        <%= favicon_link_tag asset_path('rocket.ico') %>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <div class='mymain'>

            <% if user_signed_in? %>
            <div class='mynavcontainer'>
                <%= render 'shared/nav' %>
            </div>
            <% end %>

            <div class='myyieldcontainer'>
                <% if user_signed_in? %>
                    <%= render 'shared/header' %>
                    <br/>
                    <% if notice %>
                        <%= render 'shared/alert'%>
                    <% end %>
                <% end %>
                <%= yield %>
            </div>
            
        </div>
        
        <!--bootstap 4.6.0-->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <!--custom scripts-->
        <%= javascript_pack_tag 'script' %>
    </body>
</html>

app/views/shared/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/shared/_header.html.erb
<ul class="nav myheader">
    <form class="form-inline my-2 my-lg-0 searchbar-container">
        <%= image_tag 'search.svg', size: "20x20" %>
        <input class="searchbar form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    </form>

    <div class='header-division-user'>
        <li class="nav-item">
            <%= image_tag 'info.svg', size: "20x20" %>
        </li>

        <li class="nav-item">
            <%= image_tag 'bell.svg', size: "23x23" %>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle username" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'Edit Profile', edit_user_registration_path, class:'dropdown-item'%>
                <p class='dropdown-item'>Settings</p>
                <div class="dropdown-divider"></div>
                <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:'dropdown-item'%>
            </div>
        </li>

        <div class='user-avatar'></div>
    </div>
</ul>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light flex-column">
    <br>
    <div class='logo-div'>
        <%= image_tag 'rocket.svg', size: "40x40" %>
        <%= link_to 'spaces', root_path, class:'navbar-brand'%>
    </div>
    

    <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>-->

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        
        <ul class="navbar-nav mr-auto flex-column">
            <div class='greet-user-container'>
                <li class='greet-user'>Hello <%= current_user.username %>!</li>
                <li>Let's be productive today</li>
            </div>
            
            <li class="nav-item active mysidenav">
                <%= image_tag 'home.svg', size: "20x20" %>
                <%= link_to 'Home', root_path, class:'nav-link'%>
            </li>

            <li class="nav-item mysidenav">
                <%= image_tag 'calendar.svg', size: "20x20" %>
                <%= link_to 'Calendar', root_path, class:'nav-link disabled'%>
            </li>

            <li class="nav-item mysidenav">
                <%= image_tag 'projects.svg', size: "20x20" %>
                <%= link_to 'Projects', root_path, class:'nav-link disabled'%>
                <!--<div class='sidenav-counter'><div>99</div></div>-->
            </li>

            <li class="nav-item active mysidenav">
                <%= image_tag 'categories.svg', size: "20x20" %>
                <%= link_to 'Categories', categories_path, class:'nav-link'%>
                <div class='sidenav-counter'>
                    <div id='sidenav-categories-counter'><%= @categories.count %></div>
                </div>
            </li>

            <li class="nav-item active mysidenav">
                <%= image_tag 'tasks.svg', size: "20x20" %>
                <%= link_to 'Tasks', tasks_list_path, class:'nav-link'%>
                <div class='sidenav-counter'>
                    <div id='sidenav-tasks-counter'><%= @tasks.count %>
                    </div>
                </div>
            </li>

            <br><br><br><br>

            <li class="nav-item mysidenav">
                <%= image_tag 'settings.svg', size: "20x20" %>
                <%= link_to 'Settings', root_path, class:'nav-link disabled'%>
            </li>

            <li class="nav-item active mysidenav">
                <%= image_tag 'logout.svg', size: "20x20" %>
                <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:'nav-link'%>
            </li>

        </ul>

    </div>
</nav>

app/views/tasks/edit.html.erb
<div class='container'>
    <%= form_with scope: :task, url: task_path, method: :put, remote: true do |f| %>
    <%# url attr is where the user is redirected once the form is submitted
    url: use alias for value; you can view aliases by issuing the command:
    rails routes outside rails console %>

    <div>
        <% if @task.errors.any? %>
        <ul>
            <% @task.errors.full_messages.each do |msg| %>
                <li class="alert alert-danger" role="alert" ><%= msg %></li>
            <% end %>
        </ul>
        <% end %>
    </div>


    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div>
        <%= f.label :body %>
        <%= f.text_area :body, size: '100x7' %>
    </div>

    <div>
        <%= f.label :deadline %>
        <%= f.date_field :deadline%>
    </div>

    <div>
        <%= f.label :category_id %>
        <%= f.collection_select :category_id, Category.where(user_id: current_user.id).order(:name),:id,:name, include_blank: true %>
    </div>    


    <div>
        <%= f.submit :Update, class: 'btn btn-primary' %>
    </div>

    <% end %>
</div>
    
  

app/views/tasks/index.html.erb
<div class="table table-responsive-lg">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">title</th>
                <th scope="col">body</th>
                <th scope="col">deadline</th>
                <th scope="col">id(pk)</th>
                <th scope="col">category_id(fk)</th>
                <th scope="col">category_name</th>
            </tr>
        </thead>
        <tbody>
            <% @tasks.each do |task| %>
                <tr>
                    <td scope="row"><%= task.title%></td>
                    <td><%= task.body%></td>
                    <td><%= task.deadline%></td>
                    <td><%= task.id%></td>
                    <td><%= task.category_id%></td>
                    <% c = @categories.to_a.map(&:serializable_hash) %>
                    <% c.each do |categ| %>
                        <% if (categ['id'] == task.category_id) %>
                            <td><%= categ['name']%></td>
                        <% end %>   
                    <% end %>
                    <td><%= link_to "View", task %></td>
                    <td><%= link_to "Edit", edit_task_path(task) %></td>
                    <td><%= link_to "Delete", task, method: :delete, data: { confirm: "Are you sure?" } %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>
<br>
<div>Tasks total: <%= @tasks.count %></div>
<div>Categories total: <%= @categories.count %></div>
<%= link_to "New task", new_task_path %>


<!--this is probably not needed, redundant-->

app/views/tasks/new.html.erb
<div class='container'>
        <%= form_with scope: :task, url: tasks_path, local: true do |f| %>
        <%# url attr is where the user is redirected once the form is submitted
        url: use alias for value; you can view aliases by issuing the command:
        rails routes outside rails console %>

    <div>
        <% if @task.errors.any? %>
        <ul>
            <% @task.errors.full_messages.each do |msg| %>
                <li class="alert alert-danger" role="alert" ><%= msg %></li>
            <% end %>
        </ul>
        <% end %>
    </div>


    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div>
        <%= f.label :body %>
        <%= f.text_area :body, size: '100x20' %>
    </div>

    <div>
        <%= f.label :deadline %>
        <%= f.date_field :deadline%>
    </div>

    <div>
        <%= f.label :category_id %>
        <%= f.collection_select :category_id, Category.where(user_id: current_user.id).order(:name),:id,:name, include_blank: true %>
    </div>

    <div>
        <%= f.text_field :status, value: "unfinished", type: :hidden %>
    </div>

    <div>
        <%= f.submit :Post, class: 'btn btn-primary'%>
    </div>

<% end %>
</div>

app/views/tasks/show.html.erb
<div class='container'>
    <br/>
    <h1><%= @task.title %></h1>
    <p><%= @task.body %></p>
    <p><%= @task.deadline %></p>

    <%= link_to 'Home', root_path, class: 'btn btn-primary'%>
    <%= link_to 'Edit', edit_task_path(@task), class: 'btn btn-primary'%>
    <%= link_to 'Delete', @task, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
</div>

app/views/tasks/tasks_list.html.erb
<div class='mainboard-header'>
    <h3>Tasks list</h3>
    <div class="form-group scope">
        <select class="form-control" id="sel1">
            <option selected>Today</option>
            <option>This Week</option>
            <option>This Month</option>
            <option>This Year</option>
        </select>
    </div>
</div>

<div class="table table-responsive-lg">
    <table class="table table-fixed">
        <thead>
            <tr>
                <th>title</th>
                <th>body</th>
                <th>deadline</th>
                <th>category name</th>
            </tr>
        </thead>
        <tbody>
            <% @tasks.each do |task| %>
                <tr data-link="<%= task_path(task) %>" class='mylink'>
                    <td scope="row" class='tasks-list-task-title'><%= task.title%></td>
                    <td class='tasks-list-task-body'><%= task.body%></td>
                    <td><%= task.deadline.strftime("%B %d, %Y")%></td>
                    <% c = @categories.to_a.map(&:serializable_hash) %>
                    <% c.each do |categ| %>
                        <% if (categ['id'] == task.category_id) %>
                            <td><%= categ['name']%></td>
                        <% end %>   
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>
    <br>
    <%= link_to "New Task", new_task_path %>
</div>